# Generated by Django 3.1.5 on 2021-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20210204_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link ....', max_length=255),
        ),
    ]
