# Generated by Django 3.1.5 on 2021-02-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_auto_20210207_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_imgae',
            new_name='header_image',
        ),
    ]
